// svelte-app/src/App.svelte
﻿<script>
  import { onMount } from 'svelte'

  // â”€â”€ State â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  let videoEl = null
  let canvasEl = null
  let fileInput = null

  /** 'idle' | 'scanning' | 'analyzing' | 'result' */
  let view = 'idle'

  let capturedUrl = ''
  let stream = null
  let errorMsg = ''

  /** Shown once on first visit */
  let showOnboarding = true

  /** Segmentation result object populated after ONNX inference */
  let result = null

  // â”€â”€ Camera helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  async function startCamera() {
    errorMsg = ''
    try {
      stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } }
      })
      if (videoEl) videoEl.srcObject = stream
      view = 'scanning'
    } catch (e) {
      errorMsg = 'Could not access camera: ' + e.message
    }
  }

  function stopCamera() {
    if (stream) {
      stream.getTracks().forEach(t => t.stop())
      stream = null
    }
  }

  function capturePhoto() {
    if (!videoEl || !canvasEl) return
    canvasEl.width = videoEl.videoWidth
    canvasEl.height = videoEl.videoHeight
    const ctx = canvasEl.getContext('2d')
    if (!ctx) return
    ctx.drawImage(videoEl, 0, 0, canvasEl.width, canvasEl.height)
    capturedUrl = canvasEl.toDataURL('image/jpeg', 0.92)
    stopCamera()
    runInference()
  }

  function handleFileUpload(e) {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = (ev) => {
      capturedUrl = ev.target.result
      // Draw uploaded image onto canvas so ONNX can read pixel data
      const img = new Image()
      img.crossOrigin = 'anonymous'
      img.onload = () => {
        if (!canvasEl) return
        canvasEl.width = img.naturalWidth
        canvasEl.height = img.naturalHeight
        canvasEl.getContext('2d').drawImage(img, 0, 0)
        runInference()
      }
      img.src = capturedUrl
    }
    reader.readAsDataURL(file)
    // Reset so the same file can be re-selected
    if (fileInput) fileInput.value = ''
  }

  // â”€â”€ ONNX Inference â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  /**
   * HOW TO INTEGRATE YOUR ONNX MODEL
   * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
   * 1. Install the runtime:
   *      pnpm add onnxruntime-web
   *
   * 2. Place your model file at:
   *      svelte-app/public/models/food_classifier.onnx
   *    (The public/ folder is served as-is by Vite.)
   *
   * 3. Load the session once (e.g. in onMount or a Svelte store):
   *      import * as ort from 'onnxruntime-web'
   *      const session = await ort.InferenceSession.create('/models/food_classifier.onnx')
   *
   * 4. Pre-process the canvas pixel data into a Float32 tensor:
   *      const imageData = canvasEl.getContext('2d').getImageData(0, 0, 224, 224)
   *      // Normalize [0,255] â†’ [0,1] and arrange as CHW (channels-first):
   *      const tensor = new ort.Tensor('float32', float32Data, [1, 3, 224, 224])
   *
   * 5. Run inference and read the top-1 class + score:
   *      const { output } = await session.run({ input: tensor })
   *      const scores = Array.from(output.data)
   *      const topIdx = scores.indexOf(Math.max(...scores))
   *      const label = LABELS[topIdx]        // your label map array
   *      const confidence = scores[topIdx]   // 0â€“1
   *
   * 6. Decode segmentation boxes, masks, and points, then render the overlay.
   *
   * The stub below simulates segmentation-shaped output so the UI flows end-to-end right now.
   * Replace the body of runInference() with the React app inference implementation.
   */
  async function runInference() {
    view = 'analyzing'
    result = null
    errorMsg = ''

    try {
      // â”€â”€ STUB: replace this block with real onnxruntime-web inference â”€â”€â”€â”€â”€â”€
      await new Promise(r => setTimeout(r, 1800))
      result = {
        label: 'Sample segment',
        confidence: 0.91,
        detections: [
          {
            label: 'Sample segment',
            confidence: 0.91,
            box: { x1: 32, y1: 28, x2: 210, y2: 196, width: 178, height: 168 },
            points: [[42, 30], [190, 34], [210, 152], [166, 196], [58, 182], [32, 88]],
          },
        ],
      }
      // â”€â”€ END STUB â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      view = 'result'
    } catch (e) {
      errorMsg = 'Analysis failed: ' + e.message
      view = 'scanning'
    }
  }

  function reset() {
    capturedUrl = ''
    result = null
    errorMsg = ''
    view = 'idle'
  }

  function dismissOnboarding() {
    showOnboarding = false
    // Persist so it only shows once per device
    try { localStorage.setItem('nutriscan_onboarded', '1') } catch (_) {}
  }

  onMount(() => {
    try {
      if (localStorage.getItem('nutriscan_onboarded')) showOnboarding = false
    } catch (_) {}
  })
</script>

<!-- â”€â”€ Markup â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->

<!-- Hidden canvas for pixel capture -->
<canvas bind:this={canvasEl} class="hidden-canvas" aria-hidden="true"></canvas>

<!-- Hidden file input -->
<input
  bind:this={fileInput}
  type="file"
  accept="image/*"
  class="hidden-canvas"
  aria-hidden="true"
  on:change={handleFileUpload}
/>

<!-- â”€â”€ Onboarding Modal â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->
{#if showOnboarding}
  <div class="overlay" role="dialog" aria-modal="true" aria-labelledby="onboard-title">
    <div class="modal">
      <div class="modal-header">
        <span class="modal-icon">
          <!-- Lens icon -->
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">
            <circle cx="11" cy="11" r="7"/>
            <line x1="16.5" y1="16.5" x2="22" y2="22"/>
          </svg>
        </span>
        <h2 id="onboard-title">Welcome to FoodScan</h2>
      </div>

      <p class="modal-subtitle">Identify any food and get instant nutrition info â€” entirely on-device.</p>

      <ol class="steps">
        <li>
          <div class="step-img step-img--cam">
            <!-- Placeholder: replace with a real photo of the camera viewfinder UI -->
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true">
              <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
              <circle cx="12" cy="13" r="4"/>
            </svg>
            <span class="step-img__label">Add screenshot here</span>
          </div>
          <div class="step-text">
            <strong>Open the camera</strong>
            <span>Tap <em>Scan Food</em> to launch your rear camera. Hold it steady above the dish.</span>
          </div>
        </li>
        <li>
          <div class="step-img step-img--frame">
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true">
              <polyline points="3 7 3 3 7 3"/>
              <polyline points="17 3 21 3 21 7"/>
              <polyline points="21 17 21 21 17 21"/>
              <polyline points="7 21 3 21 3 17"/>
            </svg>
            <span class="step-img__label">Add screenshot here</span>
          </div>
          <div class="step-text">
            <strong>Frame the food</strong>
            <span>Fit the main item inside the bracket guides. Good lighting gives better results.</span>
          </div>
        </li>
        <li>
          <div class="step-img step-img--shutter">
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true">
              <circle cx="12" cy="12" r="10"/>
              <circle cx="12" cy="12" r="4" fill="currentColor"/>
            </svg>
            <span class="step-img__label">Add screenshot here</span>
          </div>
          <div class="step-text">
            <strong>Tap the shutter</strong>
            <span>Press the large button to capture. The on-device ONNX model analyses the image in seconds â€” no internet needed.</span>
          </div>
        </li>
        <li>
          <div class="step-img step-img--upload">
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true">
              <polyline points="16 16 12 12 8 16"/>
              <line x1="12" y1="12" x2="12" y2="21"/>
              <path d="M20.39 18.39A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.3"/>
            </svg>
            <span class="step-img__label">Add screenshot here</span>
          </div>
          <div class="step-text">
            <strong>Or upload a photo</strong>
            <span>Tap <em>Upload Image</em> to pick a photo from your gallery instead.</span>
          </div>
        </li>
      </ol>

      <button class="btn btn--primary btn--full" on:click={dismissOnboarding}>
        Get Started
      </button>
    </div>
  </div>
{/if}

<!-- â”€â”€ App Shell â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->
<main class="shell">
  <header class="app-header">
    <span class="wordmark">NutriScan</span>
    {#if view !== 'idle'}
      <button class="btn btn--ghost btn--sm" on:click={reset}>Reset</button>
    {/if}
  </header>

  <!-- â”€â”€ Idle / Home â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->
  {#if view === 'idle'}
    <section class="home">
      <div class="hero-icon">
        <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" aria-hidden="true">
          <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
          <circle cx="12" cy="13" r="4"/>
        </svg>
      </div>
      <h1 class="home-title">What are you eating?</h1>
      <p class="home-sub">Point your camera at any food and get instant nutrition breakdown â€” processed entirely on your device.</p>

      <div class="home-actions">
        <button class="btn btn--primary btn--full" on:click={startCamera}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
            <circle cx="12" cy="13" r="4"/>
          </svg>
          Scan Food
        </button>
        <button class="btn btn--secondary btn--full" on:click={() => fileInput?.click()}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <polyline points="16 16 12 12 8 16"/><line x1="12" y1="12" x2="12" y2="21"/>
            <path d="M20.39 18.39A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.3"/>
          </svg>
          Upload Image
        </button>
      </div>

      {#if errorMsg}
        <p class="error-msg" role="alert">{errorMsg}</p>
      {/if}
    </section>
  {/if}

  <!-- â”€â”€ Scanning / Viewfinder â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->
  {#if view === 'scanning'}
    <section class="viewfinder-wrap">
      <!-- Live feed -->
      <!-- svelte-ignore a11y-media-has-caption -->
      <video bind:this={videoEl} class="viewfinder-video" autoplay playsinline></video>

      <!-- Corner bracket overlay -->
      <div class="vf-overlay" aria-hidden="true">
        <div class="vf-bracket vf-bracket--tl"></div>
        <div class="vf-bracket vf-bracket--tr"></div>
        <div class="vf-bracket vf-bracket--bl"></div>
        <div class="vf-bracket vf-bracket--br"></div>
        <div class="vf-scanline"></div>
      </div>

      <div class="vf-hint">Center the food within the frame</div>

      <!-- Controls bar -->
      <div class="vf-controls">
        <button class="btn btn--ghost btn--sm" on:click={() => { stopCamera(); view = 'idle' }}>Cancel</button>
        <button class="shutter-btn" on:click={capturePhoto} aria-label="Capture photo">
          <span class="shutter-inner"></span>
        </button>
        <button class="btn btn--ghost btn--sm" on:click={() => fileInput?.click()}>Upload</button>
      </div>
    </section>
  {/if}

  <!-- â”€â”€ Analyzing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->
  {#if view === 'analyzing'}
    <section class="analyzing">
      {#if capturedUrl}
        <img class="thumb" src={capturedUrl} alt="Captured food" />
      {/if}
      <div class="spinner" aria-label="Analysing imageâ€¦">
        <div class="spinner-ring"></div>
      </div>
      <p class="analyzing-label">Running on-device modelâ€¦</p>
      <p class="analyzing-sub">No data leaves your device</p>
    </section>
  {/if}

  <!-- â”€â”€ Result â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->
  {#if view === 'result' && result}
    <section class="result">
      {#if capturedUrl}
        <img class="result-thumb" src={capturedUrl} alt="Scanned food" />
      {/if}

      <div class="result-card">
        <div class="result-header">
          <h2 class="result-label">{result.label}</h2>
          <span class="confidence-chip">{Math.round(result.confidence * 100)}% match</span>
        </div>

        <pre class="result-json">{JSON.stringify(result.detections, null, 2)}</pre>
      </div>

      <div class="result-actions">
        <button class="btn btn--primary btn--full" on:click={startCamera}>Scan Again</button>
        <button class="btn btn--secondary btn--full" on:click={reset}>Back to Home</button>
      </div>
    </section>
  {/if}
</main>

<style>
  /* â”€â”€ Design tokens â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  :root {
    --bg:         #0e0f0e;
    --surface:    #1a1c1a;
    --border:     #2c2e2c;
    --accent:     #7ebe4e;
    --accent-dim: #5a9a35;
    --warm:       #e07c3a;
    --text:       #f0f0ee;
    --text-muted: #8a8e88;
    --radius:     0.75rem;
    font-family: 'Inter', system-ui, sans-serif;
    color-scheme: dark;
  }

  /* â”€â”€ Base â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  :global(*, *::before, *::after) { box-sizing: border-box; margin: 0; padding: 0; }
  :global(html, body) {
    background: var(--bg);
    color: var(--text);
    height: 100%;
    overscroll-behavior: none;
  }

  .hidden-canvas { display: none; }

  /* â”€â”€ Shell â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  .shell {
    display: flex;
    flex-direction: column;
    min-height: 100dvh;
    max-width: 480px;
    margin: 0 auto;
  }

  /* â”€â”€ Header â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  .app-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem 1.25rem;
    border-bottom: 1px solid var(--border);
  }
  .wordmark {
    font-size: 1.1rem;
    font-weight: 700;
    letter-spacing: -0.02em;
    color: var(--accent);
  }

  /* â”€â”€ Buttons â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  .btn {
    display: inline-flex;
    align-items: center;
    gap: 0.45rem;
    font-size: 0.95rem;
    font-weight: 600;
    border: none;
    border-radius: var(--radius);
    cursor: pointer;
    padding: 0.7rem 1.25rem;
    transition: opacity 0.15s, background 0.15s;
  }
  .btn:active { opacity: 0.8; }
  .btn--primary  { background: var(--accent); color: #0e0f0e; }
  .btn--secondary { background: var(--surface); color: var(--text); border: 1px solid var(--border); }
  .btn--ghost    { background: transparent; color: var(--text-muted); font-size: 0.85rem; padding: 0.4rem 0.75rem; }
  .btn--sm       { padding: 0.4rem 0.75rem; font-size: 0.85rem; }
  .btn--full     { width: 100%; justify-content: center; }

  /* â”€â”€ Home â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  .home {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 2rem 1.5rem;
    gap: 1rem;
    text-align: center;
  }
  .hero-icon { color: var(--accent); opacity: 0.7; }
  .home-title { font-size: 1.6rem; font-weight: 700; letter-spacing: -0.02em; line-height: 1.25; }
  .home-sub   { color: var(--text-muted); font-size: 0.9rem; line-height: 1.55; max-width: 300px; }
  .home-actions { display: flex; flex-direction: column; gap: 0.75rem; width: 100%; max-width: 320px; margin-top: 0.5rem; }
  .error-msg { color: var(--warm); font-size: 0.85rem; margin-top: 0.5rem; }

  /* â”€â”€ Viewfinder â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  .viewfinder-wrap {
    flex: 1;
    position: relative;
    display: flex;
    flex-direction: column;
    background: #000;
    overflow: hidden;
  }
  .viewfinder-video {
    width: 100%;
    flex: 1;
    object-fit: cover;
  }
  .vf-overlay {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }

  /* Bracket corners */
  .vf-bracket {
    position: absolute;
    width: 36px;
    height: 36px;
    border-color: var(--accent);
    border-style: solid;
    border-width: 0;
  }
  .vf-bracket--tl { top: 15%; left: 10%; border-top-width: 2px; border-left-width: 2px; border-top-left-radius: 4px; }
  .vf-bracket--tr { top: 15%; right: 10%; border-top-width: 2px; border-right-width: 2px; border-top-right-radius: 4px; }
  .vf-bracket--bl { bottom: 25%; left: 10%; border-bottom-width: 2px; border-left-width: 2px; border-bottom-left-radius: 4px; }
  .vf-bracket--br { bottom: 25%; right: 10%; border-bottom-width: 2px; border-right-width: 2px; border-bottom-right-radius: 4px; }

  /* Scan line */
  .vf-scanline {
    position: absolute;
    left: 10%; right: 10%;
    top: 15%;
    height: 2px;
    background: var(--accent);
    opacity: 0.55;
    animation: scanline 2s ease-in-out infinite;
  }
  @keyframes scanline {
    0%   { top: 15%; }
    50%  { top: calc(75% - 2px); }
    100% { top: 15%; }
  }

  .vf-hint {
    position: absolute;
    top: calc(75% + 8px);
    left: 0; right: 0;
    text-align: center;
    font-size: 0.78rem;
    color: var(--text-muted);
    letter-spacing: 0.03em;
  }

  .vf-controls {
    position: absolute;
    bottom: 0; left: 0; right: 0;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1.25rem 1.5rem 2rem;
    background: linear-gradient(to top, rgba(0,0,0,0.7), transparent);
  }

  /* Shutter */
  .shutter-btn {
    width: 68px; height: 68px;
    border-radius: 50%;
    border: 3px solid #fff;
    background: transparent;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: transform 0.12s;
  }
  .shutter-btn:active { transform: scale(0.93); }
  .shutter-inner {
    width: 54px; height: 54px;
    border-radius: 50%;
    background: #fff;
  }

  /* â”€â”€ Analyzing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  .analyzing {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 1.25rem;
    padding: 2rem 1.5rem;
  }
  .thumb {
    width: 180px; height: 180px;
    object-fit: cover;
    border-radius: var(--radius);
    opacity: 0.6;
  }
  .spinner { position: relative; width: 56px; height: 56px; }
  .spinner-ring {
    width: 100%; height: 100%;
    border-radius: 50%;
    border: 3px solid var(--border);
    border-top-color: var(--accent);
    animation: spin 0.8s linear infinite;
  }
  @keyframes spin { to { transform: rotate(360deg); } }
  .analyzing-label { font-weight: 600; font-size: 1rem; }
  .analyzing-sub   { color: var(--text-muted); font-size: 0.82rem; }

  /* â”€â”€ Result â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  .result {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 1.25rem 1.25rem 2rem;
  }
  .result-thumb {
    width: 100%;
    max-height: 240px;
    object-fit: cover;
    border-radius: var(--radius);
  }
  .result-card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  .result-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
  }
  .result-label { font-size: 1.3rem; font-weight: 700; }
  .confidence-chip {
    font-size: 0.78rem;
    font-weight: 600;
    background: color-mix(in srgb, var(--accent) 18%, transparent);
    color: var(--accent);
    border-radius: 999px;
    padding: 0.2rem 0.65rem;
    white-space: nowrap;
  }
.result-json {
    max-height: 260px;
    overflow: auto;
    border: 1px solid var(--border);
    border-radius: 0.5rem;
    padding: 0.85rem;
    color: var(--text);
    background: var(--bg);
    font-size: 0.72rem;
    line-height: 1.45;
    white-space: pre-wrap;
  }
  .result-actions { display: flex; flex-direction: column; gap: 0.75rem; }

  /* â”€â”€ Onboarding Modal â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  .overlay {
    position: fixed;
    inset: 0;
    background: rgba(0,0,0,0.72);
    display: flex;
    align-items: flex-end;
    justify-content: center;
    z-index: 100;
    padding: 0;
  }
  .modal {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius) var(--radius) 0 0;
    padding: 1.75rem 1.5rem 2.5rem;
    width: 100%;
    max-width: 480px;
    max-height: 88dvh;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  .modal-header {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }
  .modal-icon { color: var(--accent); }
  .modal-header h2 { font-size: 1.25rem; font-weight: 700; }
  .modal-subtitle { color: var(--text-muted); font-size: 0.88rem; line-height: 1.55; }

  /* Steps list */
  .steps {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
    margin: 0.25rem 0;
    counter-reset: steps;
  }
  .steps li {
    display: flex;
    gap: 1rem;
    align-items: flex-start;
    counter-increment: steps;
  }

  /* Placeholder image box */
  .step-img {
    flex-shrink: 0;
    width: 88px;
    height: 72px;
    border-radius: 0.5rem;
    border: 1.5px dashed var(--border);
    background: var(--bg);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 0.25rem;
    color: var(--text-muted);
    text-align: center;
  }
  .step-img--cam     { border-color: color-mix(in srgb, var(--accent) 40%, transparent); }
  .step-img--frame   { border-color: color-mix(in srgb, var(--accent) 30%, transparent); }
  .step-img--shutter { border-color: color-mix(in srgb, var(--warm)   35%, transparent); }
  .step-img--upload  { border-color: color-mix(in srgb, var(--text-muted) 40%, transparent); }
  .step-img__label {
    font-size: 0.58rem;
    color: var(--text-muted);
    opacity: 0.6;
    line-height: 1.2;
    padding: 0 0.25rem;
  }

  .step-text {
    display: flex;
    flex-direction: column;
    gap: 0.2rem;
    padding-top: 0.1rem;
  }
  .step-text strong { font-size: 0.92rem; font-weight: 700; }
  .step-text span   { font-size: 0.82rem; color: var(--text-muted); line-height: 1.5; }
  .step-text em     { font-style: normal; color: var(--accent); }
</style>

// src/App.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { ChangeEvent } from 'react'
import './App.css'
import './segmentation.css'
import { drawSegmentationOverlay } from './inference/image'
import { MODEL_OPTIONS } from './inference/models'
import { runSegmentation, warmSegmentationModels } from './inference/segmentation'
import type { ModelId, SegmentResult } from './inference/types'

// ── Types ─────────────────────────────────────────────────────────────────────

type BeforeInstallPromptEvent = Event & {
  prompt: () => Promise<void>
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>
}

type ScanRecord = {
  id: string
  source: 'camera' | 'upload'
  imageDataUrl: string
  overlayDataUrl: string
  createdAt: string
  result: SegmentResult
}

// ── Constants ─────────────────────────────────────────────────────────────────

const HISTORY_KEY = 'nutriscan_segmentation_history'
const ONBOARDING_KEY = 'nutriscan_onboarded'
const SELECTED_MODEL_KEY = 'nutriscan_selected_model'

const STEPS = [
  {
    id: 1,
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" className="step-icon">
        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
        <circle cx="12" cy="13" r="4" />
      </svg>
    ),
    title: 'Open the camera',
    body: 'The camera launches automatically. Make sure you are in a well-lit area.',
  },
  {
    id: 2,
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" className="step-icon">
        <polyline points="3 7 3 3 7 3" />
        <polyline points="17 3 21 3 21 7" />
        <polyline points="21 17 21 21 17 21" />
        <polyline points="7 21 3 21 3 17" />
      </svg>
    ),
    title: 'Frame the food',
    body: 'Center the dish inside the bracket guides. Keep the camera steady.',
  },
  {
    id: 3,
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" className="step-icon">
        <circle cx="12" cy="12" r="10" />
        <circle cx="12" cy="12" r="3" />
      </svg>
    ),
    title: 'Tap the shutter',
    body: 'Press the large button to capture. The on-device ONNX model segments the food instantly.',
  },
  {
    id: 4,
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" className="step-icon">
        <rect x="3" y="3" width="18" height="18" rx="2" />
        <polyline points="3 9 21 9" />
        <polyline points="9 21 9 9" />
      </svg>
    ),
    title: 'Upload a photo',
    body: 'Tap the gallery icon to pick an image from your library instead.',
  },
]

// ── Storage helpers ───────────────────────────────────────────────────────────

function readHistory(): ScanRecord[] {
  try {
    const raw = localStorage.getItem(HISTORY_KEY)
    const parsed = raw ? (JSON.parse(raw) as ScanRecord[]) : []
    return parsed.filter((item) =>
      Boolean(item.id && item.createdAt && item.imageDataUrl && item.overlayDataUrl && item.result?.detections),
    )
  } catch {
    return []
  }
}

function saveHistory(records: ScanRecord[]) {
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(records))
  } catch { /* quota exceeded — silently skip */ }
}

function readSelectedModel(): ModelId {
  try {
    const stored = localStorage.getItem(SELECTED_MODEL_KEY)
    return stored === 'rfdetr' ? 'rfdetr' : 'yolo'
  } catch {
    return 'yolo'
  }
}

function hasSeenOnboarding() {
  try { return localStorage.getItem(ONBOARDING_KEY) === '1' } catch { return false }
}

function formatTime(value: string) {
  return new Intl.DateTimeFormat(undefined, {
    month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit',
  }).format(new Date(value))
}

function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => {
      if (typeof reader.result === 'string') resolve(reader.result)
      else reject(new Error('Could not read image as data URL.'))
    }
    reader.onerror = () => reject(new Error('Could not read the selected image.'))
    reader.readAsDataURL(file)
  })
}

function formatScorePercent(score: number) {
  return `${(score * 100).toFixed(1)}%`
}

// ── Sub-components ────────────────────────────────────────────────────────────

function OnboardingModal({ onDismiss }: { onDismiss: () => void }) {
  return (
    <div className="modal-overlay" role="dialog" aria-modal="true" aria-label="How to use NutriScan">
      <div className="modal">
        <div className="modal-header">
          <svg viewBox="0 0 24 24" aria-hidden="true" className="modal-logo">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
            <circle cx="12" cy="13" r="4" />
          </svg>
          <h1 className="modal-title">Welcome to NutriScan</h1>
          <p className="modal-subtitle">
            Point your camera at any food and the on-device ONNX model will identify and segment it.
          </p>
        </div>

        <ol className="steps-list">
          {STEPS.map((step) => (
            <li key={step.id} className="step">
              <div className="step-placeholder">
                {step.icon}
                <span className="step-placeholder-label">Add screenshot here</span>
              </div>
              <div className="step-body">
                <strong className="step-title">{step.title}</strong>
                <span className="step-desc">{step.body}</span>
              </div>
            </li>
          ))}
        </ol>

        <button type="button" className="btn-primary" onClick={onDismiss}>
          Get Started
        </button>
      </div>
    </div>
  )
}

function DetectionList({ result }: { result: SegmentResult }) {
  const sorted = [...result.detections].sort((a, b) => b.score - a.score)
  if (sorted.length === 0) return null
  return (
    <div className="detection-list">
      {sorted.map((det, i) => (
        <div key={i} className="detection-row">
          <span className="detection-label">{det.label}</span>
          <span className="detection-score">{formatScorePercent(det.score)}</span>
          <div
            className="detection-bar"
            style={{ width: `${(det.score * 100).toFixed(1)}%` }}
            aria-hidden="true"
          />
        </div>
      ))}
    </div>
  )
}

function HistoryCard({ record }: { record: ScanRecord }) {
  const top = record.result.detections.reduce<typeof record.result.detections[0] | null>(
    (best, det) => (!best || det.score > best.score ? det : best),
    null,
  )
  return (
    <div className="history-item">
      <img src={record.overlayDataUrl} alt="Scan overlay" className="history-thumb" />
      <div className="history-meta">
        <span className="history-label">{top?.label ?? 'Unknown food'}</span>
        <span className="history-sublabel">
          {record.result.detections.length} detection{record.result.detections.length !== 1 ? 's' : ''} &middot; {record.result.modelLabel}
        </span>
        <span className="history-time">{formatTime(record.createdAt)}</span>
      </div>
    </div>
  )
}

// ── App ───────────────────────────────────────────────────────────────────────

function App() {
  const videoRef = useRef<HTMLVideoElement | null>(null)
  const canvasRef = useRef<HTMLCanvasElement | null>(null)
  const overlayCanvasRef = useRef<HTMLCanvasElement | null>(null)
  const fileInputRef = useRef<HTMLInputElement | null>(null)
  const streamRef = useRef<MediaStream | null>(null)
  const pickerOpenRef = useRef(false)

  const [isCameraActive, setIsCameraActive] = useState(false)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  const [resultRecord, setResultRecord] = useState<ScanRecord | null>(null)
  const [showHistory, setShowHistory] = useState(false)
  const [scanHistory, setScanHistory] = useState<ScanRecord[]>(() => readHistory())
  const [showOnboarding, setShowOnboarding] = useState(() => !hasSeenOnboarding())
  const [isOnline, setIsOnline] = useState(() => navigator.onLine)
  const [installPrompt, setInstallPrompt] = useState<BeforeInstallPromptEvent | null>(null)
  const [selectedModel, setSelectedModel] = useState<ModelId>(() => readSelectedModel())
  const [confidenceThreshold, setConfidenceThreshold] = useState(0.35)
  const [iouThreshold] = useState(0.5)

  const selectedModelOption = MODEL_OPTIONS.find((m) => m.id === selectedModel) ?? MODEL_OPTIONS[0]

  const stats = useMemo(() => ({
    scans: scanHistory.length,
    detections: scanHistory.reduce((sum, r) => sum + r.result.detections.length, 0),
    modelsUsed: new Set(scanHistory.map((r) => r.result.modelId)).size,
  }), [scanHistory])

  // Persist history
  useEffect(() => { saveHistory(scanHistory) }, [scanHistory])

  // Persist selected model
  useEffect(() => {
    try { localStorage.setItem(SELECTED_MODEL_KEY, selectedModel) } catch { /* noop */ }
  }, [selectedModel])

  // Online / offline
  useEffect(() => {
    const on = () => setIsOnline(true)
    const off = () => setIsOnline(false)
    window.addEventListener('online', on)
    window.addEventListener('offline', off)
    return () => { window.removeEventListener('online', on); window.removeEventListener('offline', off) }
  }, [])

  // Install prompt
  useEffect(() => {
    const handler = (e: Event) => { e.preventDefault(); setInstallPrompt(e as BeforeInstallPromptEvent) }
    const installed = () => setInstallPrompt(null)
    window.addEventListener('beforeinstallprompt', handler)
    window.addEventListener('appinstalled', installed)
    return () => {
      window.removeEventListener('beforeinstallprompt', handler)
      window.removeEventListener('appinstalled', installed)
    }
  }, [])

  // Camera
  const stopCamera = useCallback(() => {
    streamRef.current?.getTracks().forEach((t) => t.stop())
    streamRef.current = null
    if (videoRef.current) videoRef.current.srcObject = null
    setIsCameraActive(false)
  }, [])

  const startCamera = useCallback(async () => {
    stopCamera()
    setErrorMessage('')
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } },
        audio: false,
      })
      streamRef.current = stream
      if (videoRef.current) {
        videoRef.current.srcObject = stream
        await videoRef.current.play()
      }
      setIsCameraActive(true)
    } catch (err) {
      setErrorMessage(err instanceof Error ? err.message : 'Camera permission denied.')
      setIsCameraActive(false)
    }
  }, [stopCamera])

  useEffect(() => {
    startCamera()
    warmSegmentationModels().catch(() => { /* warm silently */ })
    return () => stopCamera()
  }, [startCamera, stopCamera])

  // Analyze
  const analyzeImage = useCallback(async (dataUrl: string, source: ScanRecord['source']) => {
    setIsAnalyzing(true)
    setErrorMessage('')
    setResultRecord(null)
    try {
      const { result, input } = await runSegmentation(selectedModel, dataUrl, {
        confidenceThreshold,
        iouThreshold,
      })

      // Draw segmentation overlay onto a canvas
      const oc = overlayCanvasRef.current ?? document.createElement('canvas')
      drawSegmentationOverlay(oc, input, result.detections)
      const overlayDataUrl = oc.toDataURL('image/jpeg', 0.82)

      setResultRecord({
        id: `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
        source,
        imageDataUrl: dataUrl,
        overlayDataUrl,
        createdAt: new Date().toISOString(),
        result,
      })
    } catch (err) {
      setErrorMessage(err instanceof Error ? err.message : 'Segmentation failed. Please try again.')
    } finally {
      setIsAnalyzing(false)
    }
  }, [selectedModel, confidenceThreshold, iouThreshold])

  const capturePhoto = useCallback(() => {
    const video = videoRef.current
    const canvas = canvasRef.current
    if (!video || !canvas) { setErrorMessage('Camera is not ready yet.'); return }
    if (!video.videoWidth || !video.videoHeight) {
      setErrorMessage('Wait for the camera feed to load before capturing.')
      return
    }
    canvas.width = video.videoWidth
    canvas.height = video.videoHeight
    const ctx = canvas.getContext('2d')
    if (!ctx) { setErrorMessage('Unable to prepare the photo buffer.'); return }
    ctx.drawImage(video, 0, 0)
    void analyzeImage(canvas.toDataURL('image/jpeg', 0.82), 'camera')
  }, [analyzeImage])

  const openGallery = () => {
    pickerOpenRef.current = true
    setErrorMessage('')
    const handleFocus = () => {
      setTimeout(() => {
        if (pickerOpenRef.current) {
          setErrorMessage('No image selected. Please allow access and pick a photo.')
          pickerOpenRef.current = false
        }
      }, 600)
      window.removeEventListener('focus', handleFocus)
    }
    window.addEventListener('focus', handleFocus)
    fileInputRef.current?.click()
  }

  const handleFilePick = async (e: ChangeEvent<HTMLInputElement>) => {
    pickerOpenRef.current = false
    const file = e.target.files?.[0]
    if (!file) return
    try {
      void analyzeImage(await fileToDataUrl(file), 'upload')
    } catch (err) {
      setErrorMessage(err instanceof Error ? err.message : 'Could not load the selected photo.')
    }
    e.target.value = ''
  }

  const saveResult = () => {
    if (!resultRecord) return
    setScanHistory((prev) => [resultRecord, ...prev])
    setResultRecord(null)
  }

  const takeAnother = () => setResultRecord(null)

  const dismissOnboarding = () => {
    try { localStorage.setItem(ONBOARDING_KEY, '1') } catch { /* noop */ }
    setShowOnboarding(false)
  }

  const handleInstall = async () => {
    if (!installPrompt) return
    await installPrompt.prompt()
    const { outcome } = await installPrompt.userChoice
    if (outcome === 'accepted') setInstallPrompt(null)
  }

  // ── Render ──────────────────────────────────────────────────────────────────

  return (
    <div className="app-shell">
      {showOnboarding && <OnboardingModal onDismiss={dismissOnboarding} />}

      <main className="camera-app" aria-label="NutriScan food scanner">
        <section className="camera-stage" aria-label="Camera preview">
          <video ref={videoRef} className="camera-video" muted autoPlay playsInline />
          <canvas ref={canvasRef} className="hidden-canvas" aria-hidden="true" />
          <canvas ref={overlayCanvasRef} className="hidden-canvas" aria-hidden="true" />

          {/* Top bar */}
          <div className="topbar-overlay">
            <div className="status-pill">
              <span className={`status-dot ${isOnline ? 'online' : 'offline'}`} />
              <span className="status-label">{isOnline ? 'Online' : 'Offline'}</span>
            </div>
            <div className="topbar-right">
              {installPrompt && (
                <button type="button" className="install-button" onClick={handleInstall} aria-label="Install app">
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                    <polyline points="7 10 12 15 17 10" />
                    <line x1="12" y1="15" x2="12" y2="3" />
                  </svg>
                </button>
              )}
              <button
                type="button"
                className="history-button"
                onClick={() => setShowHistory(true)}
                aria-label="View scan history"
              >
                <svg viewBox="0 0 24 24" aria-hidden="true" className="history-icon">
                  <path d="M12 8v4l3 3" />
                  <path d="M3.05 11a9 9 0 1 1 .5 4" />
                  <polyline points="3 16 3 11 8 11" />
                </svg>
                {scanHistory.length > 0 && (
                  <span className="history-badge" aria-label={`${scanHistory.length} saved scans`}>
                    {scanHistory.length > 99 ? '99+' : scanHistory.length}
                  </span>
                )}
              </button>
            </div>
          </div>

          {/* Viewfinder */}
          <div className="viewfinder" aria-hidden="true">
            <span className="vf-corner vf-tl" />
            <span className="vf-corner vf-tr" />
            <span className="vf-corner vf-bl" />
            <span className="vf-corner vf-br" />
          </div>

          {/* Camera paused placeholder */}
          {!isCameraActive && !isAnalyzing && !resultRecord && (
            <div className="camera-overlay">
              <p>Camera paused &mdash; tap the shutter to retry</p>
            </div>
          )}

          {/* Analyzing spinner */}
          {isAnalyzing && (
            <div className="analyzing-overlay" aria-live="polite">
              <div className="analyzing-spinner" aria-hidden="true" />
              <p className="analyzing-label">Running {selectedModelOption.label}&hellip;</p>
            </div>
          )}

          {/* Error banner */}
          {errorMessage && !isAnalyzing && (
            <p className="error-message" role="alert">{errorMessage}</p>
          )}

          {/* Model picker — idle only */}
          {!resultRecord && !isAnalyzing && (
            <div className="model-picker-bar">
              {MODEL_OPTIONS.map((opt) => (
                <button
                  key={opt.id}
                  type="button"
                  className={`model-chip ${selectedModel === opt.id ? 'model-chip--active' : ''}`}
                  onClick={() => setSelectedModel(opt.id)}
                >
                  {opt.label}
                </button>
              ))}
              <div className="confidence-row">
                <label htmlFor="conf-slider" className="conf-label">
                  Confidence&nbsp;<span className="conf-value">{(confidenceThreshold * 100).toFixed(0)}%</span>
                </label>
                <input
                  id="conf-slider"
                  type="range"
                  min="0.1"
                  max="0.9"
                  step="0.05"
                  value={confidenceThreshold}
                  onChange={(e) => setConfidenceThreshold(parseFloat(e.target.value))}
                  className="conf-slider"
                />
              </div>
            </div>
          )}

          {/* Result overlay */}
          {resultRecord && (
            <div className="result-overlay" role="dialog" aria-label="Scan result">
              <img
                src={resultRecord.overlayDataUrl}
                alt="Segmented food"
                className="result-bg-image"
              />
              <div className="result-sheet">
                <div className="result-sheet-header">
                  <div>
                    <p className="result-sheet-category">{resultRecord.result.modelLabel}</p>
                    <h2 className="result-sheet-name">
                      {resultRecord.result.detections.length > 0
                        ? resultRecord.result.detections.reduce((b, d) => d.score > b.score ? d : b).label
                        : 'No food detected'}
                    </h2>
                  </div>
                  <span className="result-confidence-chip">
                    {resultRecord.result.detections.length} detection{resultRecord.result.detections.length !== 1 ? 's' : ''}
                  </span>
                </div>

                <DetectionList result={resultRecord.result} />

                <p className="result-meta">
                  {resultRecord.result.elapsedMs.toFixed(0)}ms &middot; {resultRecord.result.imageWidth}&times;{resultRecord.result.imageHeight}px
                </p>

                <div className="result-sheet-actions">
                  <button type="button" className="btn-retake" onClick={takeAnother}>
                    Take Another
                  </button>
                  <button type="button" className="btn-use" onClick={saveResult}>
                    Save to History
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Bottom controls */}
          {!resultRecord && (
            <div className="controls-row">
              <button
                type="button"
                className="gallery-button"
                onClick={openGallery}
                aria-label="Upload from gallery"
                disabled={isAnalyzing}
              >
                <svg viewBox="0 0 24 24" aria-hidden="true" className="gallery-icon">
                  <rect x="3" y="3" width="18" height="18" rx="3" />
                  <circle cx="8.5" cy="8.5" r="1.5" />
                  <polyline points="21 15 16 10 5 21" />
                </svg>
              </button>

              <button
                type="button"
                className="capture-button"
                onClick={capturePhoto}
                aria-label="Take photo"
                disabled={isAnalyzing}
              >
                {isAnalyzing ? (
                  <span className="capture-spinner" aria-hidden="true" />
                ) : (
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M9 4.5 7.6 6H5.5A2.5 2.5 0 0 0 3 8.5v9A2.5 2.5 0 0 0 5.5 20h13a2.5 2.5 0 0 0 2.5-2.5v-9A2.5 2.5 0 0 0 18.5 6h-2.1L15 4.5H9Zm3 12.5a4 4 0 1 1 0-8 4 4 0 0 1 0 8Z" />
                  </svg>
                )}
              </button>

              <div className="controls-spacer" aria-hidden="true" />
            </div>
          )}

          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            className="hidden-input"
            onChange={handleFilePick}
          />
        </section>

        {/* History panel */}
        {showHistory && (
          <div className="history-panel" role="dialog" aria-modal="true" aria-label="Scan history">
            <div className="history-header">
              <div>
                <h2 className="history-title">History</h2>
                <p className="history-subtitle">
                  {stats.scans} scan{stats.scans !== 1 ? 's' : ''} &middot; {stats.detections} detections
                </p>
              </div>
              <div className="history-header-actions">
                {scanHistory.length > 0 && (
                  <button
                    type="button"
                    className="history-clear"
                    onClick={() => { setScanHistory([]); saveHistory([]) }}
                  >
                    Clear all
                  </button>
                )}
                <button
                  type="button"
                  className="history-close"
                  onClick={() => setShowHistory(false)}
                  aria-label="Close history"
                >
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                </button>
              </div>
            </div>

            {scanHistory.length === 0 ? (
              <p className="history-empty">No scans yet. Take a photo to get started.</p>
            ) : (
              <ul className="history-list">
                {scanHistory.map((item) => (
                  <li key={item.id}>
                    <HistoryCard record={item} />
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}
      </main>
    </div>
  )
}

export default App
